import { 
  Dashboard as DashboardIcon,
  Business as BusinessIcon,
  AccountTree as SubOrgIcon,
  Groups as GroupIcon,
  People as PeopleIcon,
  AccountBalanceWallet as WalletIcon,
  ReceiptLong as TransactionIcon,
  AccountBalance as LoanIcon,
  Savings as ContributionIcon,
  Gavel as ApprovalIcon,
  Assessment as ReportIcon,
  Notifications as NotificationIcon,
  Settings as SettingsIcon,
  ListAlt as AuditIcon,
  SupportAgent as SupportIcon,
  Person as ProfileIcon,
  Logout as LogoutIcon,
  FactCheck as RequestIcon,
  Help as HelpIcon,
  Payments as SavingsIcon
} from '@mui/icons-material';
import React from 'react';

export interface NavItem {
  name: string;
  path: string;
  icon: any;
}

export const NAVIGATION_CONFIG: Record<string, NavItem[]> = {
  super_admin: [
    { name: 'Dashboard', path: '/dashboard', icon: DashboardIcon },
    { name: 'Partners', path: '/dashboard/orgs', icon: BusinessIcon },
    { name: 'Sub-Organizations', path: '/dashboard/sub-orgs', icon: SubOrgIcon },
    { name: 'Groups', path: '/dashboard/groups', icon: GroupIcon },
    { name: 'Members', path: '/dashboard/members', icon: PeopleIcon },
    { name: 'Wallet System', path: '/dashboard/wallets', icon: WalletIcon },
    { name: 'Transactions', path: '/dashboard/transactions', icon: TransactionIcon },
    { name: 'Loans', path: '/dashboard/loans', icon: LoanIcon },
    { name: 'Contributions', path: '/dashboard/contributions', icon: ContributionIcon },
    { name: 'Approvals', path: '/dashboard/approvals', icon: ApprovalIcon },
    { name: 'Reports & Analytics', path: '/dashboard/audit', icon: ReportIcon },
    { name: 'Notifications', path: '/dashboard/notifications', icon: NotificationIcon },
    { name: 'System Settings', path: '/dashboard/config', icon: SettingsIcon },
    { name: 'Audit Logs', path: '/dashboard/logs', icon: AuditIcon },
    { name: 'Support & Help', path: '/dashboard/support', icon: SupportIcon },
    { name: 'Profile', path: '/dashboard/profile', icon: ProfileIcon },
  ],
  partner_admin: [
    { name: 'Dashboard', path: '/partner', icon: DashboardIcon },
    { name: 'Sub-Organizations', path: '/partner/sub-orgs', icon: SubOrgIcon },
    { name: 'Groups', path: '/partner/groups', icon: GroupIcon },
    { name: 'Members', path: '/partner/members', icon: PeopleIcon },
    { name: 'Wallet', path: '/partner/wallet', icon: WalletIcon },
    { name: 'Transactions', path: '/partner/transactions', icon: TransactionIcon },
    { name: 'Loans', path: '/partner/loans', icon: LoanIcon },
    { name: 'Contributions', path: '/partner/contributions', icon: ContributionIcon },
    { name: 'Approvals', path: '/partner/approvals', icon: ApprovalIcon },
    { name: 'Reports', path: '/partner/reports', icon: ReportIcon },
    { name: 'Notifications', path: '/partner/notifications', icon: NotificationIcon },
    { name: 'Settings', path: '/partner/settings', icon: SettingsIcon },
    { name: 'Profile', path: '/partner/profile', icon: ProfileIcon },
  ],
  sub_org_admin: [
    { name: 'Dashboard', path: '/sub-org', icon: DashboardIcon },
    { name: 'Groups', path: '/sub-org/groups', icon: GroupIcon },
    { name: 'Members', path: '/sub-org/members', icon: PeopleIcon },
    { name: 'Contributions', path: '/sub-org/contributions', icon: SavingsIcon },
    { name: 'Loans', path: '/sub-org/loans', icon: LoanIcon },
    { name: 'Wallet', path: '/sub-org/wallet', icon: WalletIcon },
    { name: 'Transactions', path: '/sub-org/transactions', icon: TransactionIcon },
    { name: 'Approvals', path: '/sub-org/approvals', icon: ApprovalIcon },
    { name: 'Reports', path: '/sub-org/reports', icon: ReportIcon },
    { name: 'Notifications', path: '/sub-org/notifications', icon: NotificationIcon },
    { name: 'Profile', path: '/sub-org/profile', icon: ProfileIcon },
  ],
  group_admin: [
    { name: 'Dashboard', path: '/group', icon: DashboardIcon },
    { name: 'Members', path: '/group/members', icon: PeopleIcon },
    { name: 'Contributions', path: '/group/contributions', icon: SavingsIcon },
    { name: 'Loans', path: '/group/loans', icon: LoanIcon },
    { name: 'Group Wallet', path: '/group/wallet', icon: WalletIcon },
    { name: 'Transactions', path: '/group/transactions', icon: TransactionIcon },
    { name: 'Requests', path: '/group/approvals', icon: RequestIcon },
    { name: 'Reports', path: '/group/reports', icon: ReportIcon },
    { name: 'Notifications', path: '/group/notifications', icon: NotificationIcon },
    { name: 'Profile', path: '/group/profile', icon: ProfileIcon },
  ],
  apex_admin: [
    { name: 'Dashboard', path: '/dashboard', icon: DashboardIcon },
    { name: 'Partners', path: '/dashboard/orgs', icon: BusinessIcon },
    { name: 'Sub-Organizations', path: '/dashboard/sub-orgs', icon: SubOrgIcon },
    { name: 'Groups', path: '/dashboard/groups', icon: GroupIcon },
    { name: 'Members', path: '/dashboard/members', icon: PeopleIcon },
    { name: 'Wallet System', path: '/dashboard/wallets', icon: WalletIcon },
    { name: 'Transactions', path: '/dashboard/transactions', icon: TransactionIcon },
    { name: 'Loans', path: '/dashboard/loans', icon: LoanIcon },
    { name: 'Contributions', path: '/dashboard/contributions', icon: ContributionIcon },
    { name: 'Approvals', path: '/dashboard/approvals', icon: ApprovalIcon },
    { name: 'Reports & Analytics', path: '/dashboard/audit', icon: ReportIcon },
    { name: 'Notifications', path: '/dashboard/notifications', icon: NotificationIcon },
    { name: 'System Settings', path: '/dashboard/config', icon: SettingsIcon },
    { name: 'Audit Logs', path: '/dashboard/logs', icon: AuditIcon },
    { name: 'Support & Help', path: '/dashboard/support', icon: SupportIcon },
    { name: 'Profile', path: '/dashboard/profile', icon: ProfileIcon },
  ],
  finance_admin: [
    { name: 'Dashboard', path: '/dashboard', icon: DashboardIcon },
    { name: 'Wallet System', path: '/dashboard/wallets', icon: WalletIcon },
    { name: 'Transactions', path: '/dashboard/transactions', icon: TransactionIcon },
    { name: 'Loans', path: '/dashboard/loans', icon: LoanIcon },
    { name: 'Contributions', path: '/dashboard/contributions', icon: ContributionIcon },
    { name: 'Reports', path: '/dashboard/audit', icon: ReportIcon },
    { name: 'Notifications', path: '/dashboard/notifications', icon: NotificationIcon },
    { name: 'Profile', path: '/dashboard/profile', icon: ProfileIcon },
  ],
  auditor: [
    { name: 'Dashboard', path: '/dashboard', icon: DashboardIcon },
    { name: 'Audit Logs', path: '/dashboard/logs', icon: AuditIcon },
    { name: 'Transactions', path: '/dashboard/transactions', icon: TransactionIcon },
    { name: 'Reports', path: '/dashboard/audit', icon: ReportIcon },
    { name: 'Notifications', path: '/dashboard/notifications', icon: NotificationIcon },
    { name: 'Profile', path: '/dashboard/profile', icon: ProfileIcon },
  ],
  member: [
    { name: 'Dashboard', path: '/member', icon: DashboardIcon },
    { name: 'Savings', path: '/member/savings', icon: SavingsIcon },
    { name: 'Loans', path: '/member/loans', icon: LoanIcon },
    { name: 'Wallet', path: '/member/wallet', icon: WalletIcon },
    { name: 'Transactions', path: '/member/transactions', icon: TransactionIcon },
    { name: 'Notifications', path: '/member/notifications', icon: NotificationIcon },
    { name: 'Profile', path: '/member/profile', icon: ProfileIcon },
    { name: 'Help', path: '/member/support', icon: HelpIcon },
  ],
};
